FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -o /app/backend \
    ./examples/backend


FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/backend ./backend

EXPOSE 8001

CMD ["./backend"]